addons:
  chrome: stable
  artifacts:
    paths:
      - $(ls test/.tmp/diff/*.png | tr "\n" ":")

dist: trusty
language: node_js

# Leave node_js version blank to
# use version in `.nvmrc`
node_js:

cache:
  directories:
    - node_modules

env:
  - TEST_SUITE=e2e
  - TEST_SUITE=functional
  - TEST_SUITE=lint

install:
  - npm install -g grunt-cli
  - npm install

before_script:
  - export TZ=America/New_York
  - if [ $TEST_SUITE != lint ]; then npm run build; fi

script:
  - if [ $TEST_SUITE = e2e ]; then (npm run quickstart &) && sleep 5; fi
  - npm run $TEST_SUITE:ci
  - if [ $TEST_SUITE = e2e ]; then npm run stop; fi
  - if [ $TRAVIS_EVENT_TYPE = cron ] && [ $TEST_SUITE = e2e ]; then npm run e2e:ci:bs; fi

# Include additional stages to the above script "jobs"
jobs:
  include:
    - stage: deploy to demo server
      before_install: skip
      install: skip
      script: skip
      deploy:
        - provider: script
          script: ./scripts/jenkins-deploy.sh -b master -w
          skip_cleanup: true

    - stage: deploy nightly build
      before_install: skip
      install: skip
      script: skip
      deploy:
        - provider: script
          script: ./scripts/publish-nightly.sh
          skip_cleanup: true

# Specify stage(s) order and conditionals per stage
stages:
  - name: test
    # Need "push" here too so it reruns when you push to a pull request
    if: type IN (push, pull_request)

  - deploy nightly build
    if: branch = master AND type = cron

  - deploy to demo server
    if: branch = master AND type = push
