# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Cache multiple paths
      uses: actions/cache@v2
      with:
        path: node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}

    - name: Setup timezone
      uses: zcong1993/setup-timezone@master
      with:
        timezone: America/New_York

    - name: Install Dependencies
      run: npm i

    - name: Build
      run: npm run build

    - name: Run Lint Checks
      run: npm run lint:ci

    - name: Run functional tests
      run: npm run functional:ci

    - name: Run e2e tests
      run:  (npm run quickstart &) && sleep 5; npm run e2e:group0:ci;

    - name: Explain why this job ran
      uses: monacorp/action-name@main
      with:
       entrypoint: /bin/echo
       args: The ${{ github.event_name }} event triggered this step. (We want to trigger jenkins on merge)
